enum SvgNames {
  Search = 'search',
  Settings = 'settings',
  PaginationLeft = 'pagination-left',
  PaginationRight = 'pagination-right',
  ThreeDots = 'three-dots',
  Update = 'update',
  Burger = 'burger-menu',
  Copy = 'copy',
  Edit = 'edit',
  Star = 'star',
  Favorite = 'favorite',
  MapMarker = 'map-marker',

  Plus = 'plus',
  Plus2 = 'plus2',
  PlusRound = 'plus-round',
  Plus3 = 'icons-plus',
  Plus4 = 'icons-plus-black',
  Check = 'check',
  CheckThin = 'check-thin',
  CloseRound = 'close-round',
  CloseThin = 'close-thin',
  Pencil = 'pencil',

  Hiking = 'hiking',
  Running = 'running',
  Walking = 'walking',
  Cycling = 'cycling',

  Postgresql = 'postgresql',
  Jsonwebtokens = 'jsonwebtokens',
  Prisma = 'prisma',
  Nestjs = 'nestjs',
  Github = 'github-in-circle',
  Webpack = 'webpack',
  Typescript = 'typescript',
}

export default SvgNames;
